[target.xtensa-esp32s3-espidf]
runner = "probe-rs run --chip=esp32s3"

[env]
DEFMT_LOG="info"

[build]
rustflags = [
  "-C", "link-arg=-nostartfiles",
]

target = "xtensa-esp32s3-espidf"

[unstable]
build-std = ["alloc", "core"]
